export type DashboardDecision = "Qualified" | "Watch" | "No Bet";

export type WorkspaceFixture = {
  id: string;
  fixture: string;
  competition: string;
  kickoff: string;
  market: string;
  modelProbability: string;
  fairOdds: string;
  bestPrice: string;
  ev: string;
  minPlayablePrice: string;
  confidence: string;
  riskFlags: string[];
  decision: DashboardDecision;
  explanation: string;
  closingLineMove: string;
  sampleResultStatus: "Win" | "Loss" | "Push" | "Pending";
};

export const workspaceFixtures: WorkspaceFixture[] = [
  {
    id: "man-city-vs-aston-villa",
    fixture: "Man City vs Aston Villa",
    competition: "Premier League",
    kickoff: "Sat 17:30",
    market: "Home Win",
    modelProbability: "58.4%",
    fairOdds: "1.71",
    bestPrice: "1.82",
    ev: "+6.4%",
    minPlayablePrice: "1.78",
    confidence: "Medium",
    riskFlags: ["Lineups pending", "Late market drift"],
    decision: "Watch",
    explanation: "Price is above fair but lineup uncertainty keeps this in watch mode for now.",
    closingLineMove: "+1.8%",
    sampleResultStatus: "Pending",
  },
  {
    id: "arsenal-vs-newcastle",
    fixture: "Arsenal vs Newcastle",
    competition: "Premier League",
    kickoff: "Sun 14:00",
    market: "Over 2.5",
    modelProbability: "52.1%",
    fairOdds: "1.92",
    bestPrice: "1.83",
    ev: "-4.7%",
    minPlayablePrice: "1.89",
    confidence: "Medium",
    riskFlags: ["Price below threshold"],
    decision: "No Bet",
    explanation: "Current price is short relative to model fair odds, so this remains a no-bet.",
    closingLineMove: "-1.1%",
    sampleResultStatus: "Pending",
  },
  {
    id: "inter-vs-milan",
    fixture: "Inter vs Milan",
    competition: "Serie A",
    kickoff: "Sun 19:45",
    market: "BTTS Yes",
    modelProbability: "56.8%",
    fairOdds: "1.76",
    bestPrice: "1.91",
    ev: "+8.5%",
    minPlayablePrice: "1.84",
    confidence: "Medium-high",
    riskFlags: ["Derby volatility", "Lineups pending", "Market liquidity acceptable"],
    decision: "Qualified",
    explanation:
      "The model prices BTTS Yes at 56.8%, implying fair odds of 1.76. Current best price is 1.91, clearing the minimum playable threshold after derby-volatility adjustment.",
    closingLineMove: "+3.7%",
    sampleResultStatus: "Win",
  },
  {
    id: "dortmund-vs-leverkusen",
    fixture: "Dortmund vs Leverkusen",
    competition: "Bundesliga",
    kickoff: "Sat 15:30",
    market: "Over 2.5",
    modelProbability: "55.6%",
    fairOdds: "1.80",
    bestPrice: "1.86",
    ev: "+3.3%",
    minPlayablePrice: "1.84",
    confidence: "Medium",
    riskFlags: ["High tempo variance"],
    decision: "Watch",
    explanation: "Edge is positive but sits close to threshold after variance controls.",
    closingLineMove: "+0.8%",
    sampleResultStatus: "Pending",
  },
  {
    id: "psg-vs-lille",
    fixture: "PSG vs Lille",
    competition: "Ligue 1",
    kickoff: "Fri 20:00",
    market: "Home Win",
    modelProbability: "63.2%",
    fairOdds: "1.58",
    bestPrice: "1.69",
    ev: "+7.1%",
    minPlayablePrice: "1.65",
    confidence: "High",
    riskFlags: ["Strong model agreement"],
    decision: "Qualified",
    explanation: "Home win remains qualified with clear value above threshold and stable line movement.",
    closingLineMove: "+2.6%",
    sampleResultStatus: "Win",
  },
  {
    id: "real-sociedad-vs-sevilla",
    fixture: "Real Sociedad vs Sevilla",
    competition: "La Liga",
    kickoff: "Sat 18:00",
    market: "Under 2.5",
    modelProbability: "57.9%",
    fairOdds: "1.73",
    bestPrice: "1.84",
    ev: "+6.4%",
    minPlayablePrice: "1.80",
    confidence: "Medium-high",
    riskFlags: ["Home bias correction"],
    decision: "Qualified",
    explanation: "Pace projection remains below league average, supporting an under market edge.",
    closingLineMove: "+2.1%",
    sampleResultStatus: "Win",
  },
  {
    id: "juventus-vs-atalanta",
    fixture: "Juventus vs Atalanta",
    competition: "Serie A",
    kickoff: "Sun 17:00",
    market: "BTTS Yes",
    modelProbability: "51.1%",
    fairOdds: "1.96",
    bestPrice: "1.89",
    ev: "-3.6%",
    minPlayablePrice: "1.95",
    confidence: "Medium",
    riskFlags: ["Price below threshold", "Market drift"],
    decision: "No Bet",
    explanation: "Model edge disappears once threshold and drift adjustments are applied.",
    closingLineMove: "-0.9%",
    sampleResultStatus: "Pending",
  },
  {
    id: "liverpool-vs-brighton",
    fixture: "Liverpool vs Brighton",
    competition: "Premier League",
    kickoff: "Sun 16:30",
    market: "Over 2.5",
    modelProbability: "60.4%",
    fairOdds: "1.66",
    bestPrice: "1.72",
    ev: "+3.6%",
    minPlayablePrice: "1.71",
    confidence: "Medium",
    riskFlags: ["High variance market"],
    decision: "Watch",
    explanation: "Edge is narrow and remains in watch mode pending late lineup context.",
    closingLineMove: "+0.6%",
    sampleResultStatus: "Loss",
  },
  {
    id: "porto-vs-benfica",
    fixture: "Porto vs Benfica",
    competition: "Primeira Liga",
    kickoff: "Sat 20:30",
    market: "Draw No Bet Home",
    modelProbability: "49.8%",
    fairOdds: "2.01",
    bestPrice: "2.16",
    ev: "+7.5%",
    minPlayablePrice: "2.08",
    confidence: "Medium-high",
    riskFlags: ["Derby volatility", "Strong model agreement"],
    decision: "Qualified",
    explanation: "Price materially exceeds model fair line, surviving volatility buffer adjustments.",
    closingLineMove: "+2.9%",
    sampleResultStatus: "Pending",
  },
  {
    id: "ajax-vs-psv",
    fixture: "Ajax vs PSV",
    competition: "Eredivisie",
    kickoff: "Sun 13:30",
    market: "BTTS Yes",
    modelProbability: "62.0%",
    fairOdds: "1.61",
    bestPrice: "1.67",
    ev: "+3.7%",
    minPlayablePrice: "1.66",
    confidence: "Medium",
    riskFlags: ["Lineups pending"],
    decision: "Watch",
    explanation: "Slight positive edge but confidence held at watch level until confirmed lineups.",
    closingLineMove: "+0.9%",
    sampleResultStatus: "Pending",
  },
  {
    id: "sporting-vs-braga",
    fixture: "Sporting vs Braga",
    competition: "Primeira Liga",
    kickoff: "Mon 20:15",
    market: "Home Win",
    modelProbability: "55.2%",
    fairOdds: "1.81",
    bestPrice: "1.75",
    ev: "-3.3%",
    minPlayablePrice: "1.83",
    confidence: "Medium",
    riskFlags: ["Price below threshold", "Low liquidity"],
    decision: "No Bet",
    explanation: "Market price sits below required line and liquidity does not justify execution.",
    closingLineMove: "-1.5%",
    sampleResultStatus: "Pending",
  },
  {
    id: "napoli-vs-fiorentina",
    fixture: "Napoli vs Fiorentina",
    competition: "Serie A",
    kickoff: "Sat 19:45",
    market: "Over 2.5",
    modelProbability: "57.1%",
    fairOdds: "1.75",
    bestPrice: "1.88",
    ev: "+7.4%",
    minPlayablePrice: "1.82",
    confidence: "Medium-high",
    riskFlags: ["Strong model agreement"],
    decision: "Qualified",
    explanation: "Projected shot volume supports over pricing and the market remains above trigger level.",
    closingLineMove: "+3.3%",
    sampleResultStatus: "Pending",
  },
  {
    id: "marseille-vs-monaco",
    fixture: "Marseille vs Monaco",
    competition: "Ligue 1",
    kickoff: "Sun 20:00",
    market: "BTTS Yes",
    modelProbability: "54.0%",
    fairOdds: "1.85",
    bestPrice: "1.87",
    ev: "+1.1%",
    minPlayablePrice: "1.88",
    confidence: "Medium",
    riskFlags: ["High variance market"],
    decision: "Watch",
    explanation: "Near-threshold edge remains in watch state until price improves by one tick.",
    closingLineMove: "+0.3%",
    sampleResultStatus: "Pending",
  },
  {
    id: "atletico-vs-valencia",
    fixture: "Atletico vs Valencia",
    competition: "La Liga",
    kickoff: "Sun 18:30",
    market: "Under 2.5",
    modelProbability: "59.2%",
    fairOdds: "1.69",
    bestPrice: "1.62",
    ev: "-4.1%",
    minPlayablePrice: "1.72",
    confidence: "Medium-high",
    riskFlags: ["Price below threshold"],
    decision: "No Bet",
    explanation: "Defensive profile is attractive, but available price remains short versus fair.",
    closingLineMove: "-1.9%",
    sampleResultStatus: "Pending",
  },
  {
    id: "celtic-vs-rangers",
    fixture: "Celtic vs Rangers",
    competition: "Scottish Premiership",
    kickoff: "Sun 12:00",
    market: "Over 2.5",
    modelProbability: "53.4%",
    fairOdds: "1.87",
    bestPrice: "1.95",
    ev: "+4.3%",
    minPlayablePrice: "1.91",
    confidence: "Medium",
    riskFlags: ["Derby volatility", "Lineups pending"],
    decision: "Watch",
    explanation: "Edge is playable but derby profile keeps this in watch state pre-lineups.",
    closingLineMove: "+1.2%",
    sampleResultStatus: "Pending",
  },
  {
    id: "bayern-vs-leipzig",
    fixture: "Bayern vs Leipzig",
    competition: "Bundesliga",
    kickoff: "Sat 17:30",
    market: "BTTS Yes",
    modelProbability: "58.7%",
    fairOdds: "1.70",
    bestPrice: "1.78",
    ev: "+4.7%",
    minPlayablePrice: "1.75",
    confidence: "Medium-high",
    riskFlags: ["Strong model agreement", "High variance market"],
    decision: "Qualified",
    explanation: "Model edge persists with sufficient buffer after variance controls.",
    closingLineMove: "+1.9%",
    sampleResultStatus: "Pending",
  },
];

export const selectedWorkspaceFixture = workspaceFixtures[2];

export type DashboardFixture = WorkspaceFixture;

export const dashboardFixtures = workspaceFixtures;

export const dashboardSelectedFixture = dashboardFixtures.find((fixture) => fixture.id === "inter-vs-milan") ?? dashboardFixtures[0];

export const dashboardSummaryMetrics = [
  { label: "Qualified edges", value: "4", hint: "Markets clearing threshold" },
  { label: "Watchlist markets", value: "6", hint: "Pending lineups or drift checks" },
  { label: "No-bet count", value: "5", hint: "Disciplined pass decisions" },
  { label: "Average sample EV", value: "+5.8%", hint: "Qualified edges only" },
  { label: "Sample CLV", value: "+1.4%", hint: "Versus closing lines" },
  { label: "Risk flags open", value: "9", hint: "Active review queue" },
];

export const dashboardRiskQueue = [
  { flag: "Lineups pending", count: 3, level: "medium" as const },
  { flag: "Derby volatility", count: 2, level: "high" as const },
  { flag: "Price below threshold", count: 3, level: "high" as const },
  { flag: "Market drift", count: 1, level: "medium" as const },
  { flag: "Low liquidity", count: 1, level: "low" as const },
  { flag: "Strong model agreement", count: 4, level: "low" as const },
];

export const resultsLedgerRows = [
  {
    date: "2026-06-08",
    fixture: "Inter vs Roma",
    market: "BTTS Yes",
    price: "1.84",
    closingPrice: "1.77",
    clv: "+3.8%",
    decision: "Qualified" as DashboardDecision,
    result: "Win",
    notes: "Edge held into close",
  },
  {
    date: "2026-06-10",
    fixture: "Liverpool vs Brighton",
    market: "Over 2.5",
    price: "1.93",
    closingPrice: "1.95",
    clv: "-1.0%",
    decision: "Watch" as DashboardDecision,
    result: "Loss",
    notes: "No-bet discipline missed",
  },
  {
    date: "2026-06-11",
    fixture: "PSG vs Lille",
    market: "Home Win",
    price: "1.62",
    closingPrice: "1.57",
    clv: "+3.1%",
    decision: "Qualified" as DashboardDecision,
    result: "Win",
    notes: "Qualified via drift",
  },
  {
    date: "2026-06-13",
    fixture: "Milan vs Lazio",
    market: "Draw No Bet",
    price: "1.88",
    closingPrice: "1.88",
    clv: "0.0%",
    decision: "Watch" as DashboardDecision,
    result: "Push",
    notes: "Flat close",
  },
  {
    date: "2026-06-15",
    fixture: "Real Sociedad vs Sevilla",
    market: "Under 2.5",
    price: "1.84",
    closingPrice: "1.78",
    clv: "+3.4%",
    decision: "Qualified" as DashboardDecision,
    result: "Win",
    notes: "Low-event profile held",
  },
];

export const sampleClvTrend = [
  { pick: "P1", value: 0.8 },
  { pick: "P2", value: 1.6 },
  { pick: "P3", value: 0.4 },
  { pick: "P4", value: 2.1 },
  { pick: "P5", value: 1.4 },
  { pick: "P6", value: 1.9 },
  { pick: "P7", value: 0.9 },
  { pick: "P8", value: 2.3 },
];

export const marketCoverageItems = [
  { market: "1X2", status: "Core" },
  { market: "Over/Under 2.5", status: "Core" },
  { market: "BTTS", status: "Core" },
  { market: "Draw No Bet", status: "Core" },
  { market: "Double Chance", status: "Core" },
  { market: "Asian Handicap", status: "Later" },
];

export const workflowSteps = [
  {
    title: "Fixture data",
    text: "Competition context, schedule load, and baseline team inputs.",
    value: "480+ weekly fixtures",
  },
  {
    title: "Model probability",
    text: "Outcome likelihood estimated with calibrated football model assumptions.",
    value: "BTTS 56.8%",
  },
  {
    title: "Fair odds",
    text: "Probability translated into fair market pricing for execution decisions.",
    value: "Fair 1.76",
  },
  {
    title: "Market comparison",
    text: "Best available price compared against fair line and minimum threshold.",
    value: "Best 1.91",
  },
  {
    title: "Risk filter",
    text: "Lineups, liquidity, and volatility flags are applied before status assignment.",
    value: "3 active flags",
  },
  {
    title: "Decision",
    text: "Qualified, Watch, or No Bet with explanation and preview stake guidance.",
    value: "Qualified",
  },
];

export const betHistoryPreviewRows = [
  {
    date: "2026-06-11",
    fixture: "Inter vs Roma",
    market: "BTTS Yes",
    priceTaken: "1.84",
    closingPrice: "1.77",
    clv: "+3.8%",
    result: "Win",
    notes: "Edge held into close",
  },
  {
    date: "2026-06-12",
    fixture: "Liverpool vs Brighton",
    market: "Over 2.5",
    priceTaken: "1.93",
    closingPrice: "1.95",
    clv: "-1.0%",
    result: "Loss",
    notes: "No edge at close",
  },
  {
    date: "2026-06-13",
    fixture: "PSG vs Lille",
    market: "Home Win",
    priceTaken: "1.62",
    closingPrice: "1.57",
    clv: "+3.1%",
    result: "Win",
    notes: "Qualified via price drift",
  },
  {
    date: "2026-06-14",
    fixture: "Milan vs Lazio",
    market: "Draw No Bet",
    priceTaken: "1.88",
    closingPrice: "1.88",
    clv: "0.0%",
    result: "Push",
    notes: "Flat close",
  },
];

export const simulationStats = [
  { label: "Bankroll drawdown preview", value: "-9.2%" },
  { label: "Simulated variance path", value: "14-week sample" },
  { label: "No-bet rate", value: "41%" },
  { label: "Qualified edge distribution", value: "+1.2% to +9.4%" },
  { label: "Risk exposure", value: "Medium" },
];
